version: '2'

services:
  # External Services
  postgres:
    container_name: "postgres10"
    image: "postgres:10.1"
    ports:
      - "5432:5432"
  redis:
    container_name: "redis2.8"
    image: "redis:2.8"
    ports:
      - "6379:6379"
  ngrok:
    container_name: ngrok
    image: "wernight/ngrok"
    ports:
      - "4040:4040"
    command: "ngrok http server:5000"

  # Internal Components
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file: .env
    links:
      - postgres
    depends_on:
      - ngrok

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    env_file: .env
    depends_on:
      - redis
    links:
      - redis




