"""empty message

Revision ID: 40bb183f993a
Revises: 9c4e36ed1254
Create Date: 2017-08-16 18:35:53.427614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40bb183f993a'
down_revision = '9c4e36ed1254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authentications', sa.Column('public_key', sa.String(), nullable=True))
    op.add_column('authentications', sa.Column('server_version', sa.String(), nullable=True))
    op.drop_column('authentications', 'oauth_client_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authentications', sa.Column('oauth_client_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('authentications', 'server_version')
    op.drop_column('authentications', 'public_key')
    # ### end Alembic commands ###
