"""empty message

Revision ID: 5e6baa172f80
Revises: cace8299986e
Create Date: 2017-09-18 06:27:33.127883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e6baa172f80'
down_revision = 'cace8299986e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_states',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issue_change_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('from_state_id', sa.Integer(), nullable=True),
    sa.Column('to_state_id', sa.Integer(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_state_id'], ['issue_states.id'], ),
    sa.ForeignKeyConstraint(['to_state_id'], ['issue_states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_change_logs')
    op.drop_table('issue_states')
    # ### end Alembic commands ###
