"""empty message

Revision ID: 684845248459
Revises: 40bb183f993a
Create Date: 2017-08-19 16:47:13.469940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684845248459'
down_revision = '40bb183f993a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authentications', sa.Column('baseUrl', sa.String(), nullable=True))
    op.add_column('authentications', sa.Column('clientKey', sa.String(), nullable=True))
    op.add_column('authentications', sa.Column('eventType', sa.String(), nullable=True))
    op.add_column('authentications', sa.Column('pluginsVersion', sa.String(), nullable=True))
    op.add_column('authentications', sa.Column('productType', sa.String(), nullable=True))
    op.add_column('authentications', sa.Column('publicKey', sa.String(), nullable=True))
    op.add_column('authentications', sa.Column('serverVersion', sa.String(), nullable=True))
    op.add_column('authentications', sa.Column('serviceEntitlementNumber', sa.String(), nullable=True))
    op.add_column('authentications', sa.Column('sharedSecret', sa.String(), nullable=True))
    op.drop_column('authentications', 'client_key')
    op.drop_column('authentications', 'plugins_version')
    op.drop_column('authentications', 'base_url')
    op.drop_column('authentications', 'server_version')
    op.drop_column('authentications', 'shared_secret')
    op.drop_column('authentications', 'public_key')
    op.drop_column('authentications', 'product_type')
    op.drop_column('authentications', 'event_type')
    op.drop_column('authentications', 'service_entitlement_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authentications', sa.Column('service_entitlement_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('authentications', sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('authentications', sa.Column('product_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('authentications', sa.Column('public_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('authentications', sa.Column('shared_secret', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('authentications', sa.Column('server_version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('authentications', sa.Column('base_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('authentications', sa.Column('plugins_version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('authentications', sa.Column('client_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('authentications', 'sharedSecret')
    op.drop_column('authentications', 'serviceEntitlementNumber')
    op.drop_column('authentications', 'serverVersion')
    op.drop_column('authentications', 'publicKey')
    op.drop_column('authentications', 'productType')
    op.drop_column('authentications', 'pluginsVersion')
    op.drop_column('authentications', 'eventType')
    op.drop_column('authentications', 'clientKey')
    op.drop_column('authentications', 'baseUrl')
    # ### end Alembic commands ###
